---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: Install nodejs
    apt: name=nodejs state=present update_cache=true
    become: yes
  
  - name: Install node
    apt: name=node state=present update_cache=true
    become: yes
  
  - name: Install np
    apt: name=npm state=present update_cache=true
    become: yes
  
  - name: Install n
    npm: name=n global=yes state=present
    become: yes
  
  - command: n stable
    become: yes

  - name: Install forever
    npm: name=forever state=present global=yes
    become: yes
  
  - name: Install git
    apt: name=git state=present update_cache=true
    become: yes
  
  - name: Clone App git repo
    git: repo=https://github.com/CSC-DevOps/App.git dest=App clone=yes update=yes accept_hostkey=yes
  
  - name: Install npm packages
    command: npm install chdir=App/
    become: yes

  - name: Run the app using forever and node
    command: forever start main.js 34567 chdir=App/

  - name: Ensure latest version - bash
    apt: name=bash state=latest
    become: yes

  - name: Ensure latest version - openssl
    apt: name=openssl state=latest
    become: yes

  - name: Ensure latest version - openssh-client
    apt: name=openssh-client state=latest
    become: yes

  - name: Ensure latest version - openssh-server
    apt: name=openssh-server state=latest
    become: yes

  - name: Remove contents in /tmp/*
    file: path=/tmp state=absent
    become: yes
